baseURL: "http://arm64hypervisor.com/"
title: ARM64 Hypervisor
theme: PaperMod
googleAnalytics: G-DDM8356YPK

params:
    env: production
    description: ""
    author: Mushahid Hussain
    defaultTheme: auto
      # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
      # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]
    profileMode:
        enabled: false
        title: ARM64 Hypervisor
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags
    homeInfoParams:
        Title: ""
        Content: >
            Welcome to ARM64/AARCH64 Hypervisor blog. I'm Mushahid Hussain and I'll be writing about Hypervisor and Virtualization on on this blog. Checkout my series on building a hypervisor!
    socialIcons:
        - name: github
          url: "https://github.com/sikkiladho/leo"
        - name: linkedin
          url: "http://linkedin.com/in/mhussainshar"
